-- STEP 1 - DATA EXPLORATION 
SELECT 'Total sales amount' AS Measure_name, SUM([sales_amount]) AS Measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Total quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Total price' , AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total no of orders' , COUNT(DISTINCT[order_number]) FROM gold.fact_sales
UNION ALL
SELECT 'Total no of products' , COUNT([product_name]) FROM gold.dim_products
UNION ALL 
SELECT 'Total no of customers' , COUNT([customer_key]) FROM gold.dim_customers

--------------------------------------------------------------
-- STEP 2 - DIMENSION EXPLORATION 
-- customer table 
	SELECT DISTINCT
		country -- based on countries they live
	FROM gold.dim_customers;

	SELECT DISTINCT
		marital_status -- based on marital status
	FROM gold.dim_customers;

	SELECT DISTINCT  
		gender -- based on the gender of the customer 
	FROM gold.dim_customers ;

-- products table
	SELECT DISTINCT 
		category -- based on the category of the product 
	FROM gold.dim_products ;

	SELECT DISTINCT 
		subcategory
	FROM gold.dim_products ;

-----------------------------------------------------------------
-- STEP 3 - DATE EXPLORATION
-- customers table
	SELECT 
		MAX(birthdate) AS oldest_customer,
		MIN(birthdate) AS yougest_customer
	FROM gold.dim_customers ;

	SELECT 
		MAX(create_date) AS newest_date,
		MIN(create_date) AS oldest_date
	FROM gold.dim_customers;

-- products table 
	SELECT 
		MAX(start_date) newest_product_date,
		MIN(start_date) oldest_product_date
	FROM gold.dim_products;

-- sales table
	SELECT 
		MAX(due_date) AS highest_due_date,
		MIN(due_date) AS oldest_due_date
	FROM gold.fact_sales;

	SELECT 
		MAX(shipping_date) AS highest_ship_date,
		MIN(shipping_date) AS lowest_ship_date
	FROM gold.fact_sales;

	SELECT 
		MAX(order_date) AS highest_order_date,
		MIN(order_date) AS lowest_order_date
	FROM gold.fact_sales;

----------------------------------------------------------------------
-- STEP 4 - MEASURE EXPLORATION
	-- Find the Total Sales
	SELECT 
	SUM(sales_amount) AS total_sales 
	FROM gold.fact_sales

	-- Find how many items are sold
	SELECT 
	SUM(quantity) AS total_quantity 
	FROM gold.fact_sales

	-- Find the average selling price
	SELECT 
	AVG(price) AS avg_price 
	FROM gold.fact_sales

	-- Find the Total number of Orders
	SELECT 
	COUNT(order_number) AS total_orders 
	FROM gold.fact_sales

	SELECT 
	COUNT(DISTINCT order_number) AS total_orders 
	FROM gold.fact_sales

	-- Find the total number of products
	SELECT 
	COUNT(product_name) AS total_products 
	FROM gold.dim_products

	-- Find the total number of customers
	SELECT 
	COUNT(customer_key) AS total_customers 
	FROM gold.dim_customers;

	-- Find the total number of customers that has placed an order
	SELECT 
	COUNT(DISTINCT customer_key) AS total_customers 
	FROM gold.fact_sales;


-----------------------------------------------------------------------------------
-- STEP 5 - MAGNITUDE ANALYSIS (MEASURES BY DIMENSIONS)

-- total customers by country 
SELECT 
	country,
	COUNT([customer_key]) AS Total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_customers DESC 


-- total customers by gender 
SELECT 
	gender,
	COUNT([customer_key]) AS Total_customers_by 
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_customers_by DESC


-- total products by category 
SELECT 
	category,
	COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC


-- Average cost by category 
SELECT 
	category,
	AVG(cost) AS Average_cost 
FROM gold.dim_products
GROUP BY category
ORDER BY Average_cost DESC


-- Total revenue genrated by each catgory 
SELECT 
pr.category,
SUM(fs.sales_amount) AS Total_sales_by_products 
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS pr
ON fs.product_key = pr.product_key
GROUP BY pr.category
ORDER BY Total_sales_by_products DESC


--Total revenue generated by each customer [customer_key][customer_id]
	SELECT 
		cu.customer_key,
		cu.first_name,
		cu.last_name,
		SUM(sales_amount) AS Total_revenue_by_customer
	FROM gold.dim_customers AS cu
	LEFT JOIN gold.fact_sales AS fs
	ON cu.customer_key = fs.customer_key
	GROUP BY  cu.customer_key,
			  cu.first_name,
			  cu.last_name		
	ORDER BY Total_revenue_by_customer desc


-- distribution of items sold across countries ?
SELECT 
	cu.country,
	SUM(fs.quantity) AS total_items_sold_by_country
FROM gold.dim_customers AS cu
LEFT JOIN gold.fact_sales AS fs
ON cu.customer_key = fs.customer_key
GROUP BY cu.country
ORDER BY total_items_sold_by_country DESC

-----------------------------------------------------------------------------------

--STEP 6 - RANKING (DIMENSIONS BY MEASURES)

--which 5 product genrate the highest revenue ?
SELECT TOP 5 
	pr.product_name,
	SUM(sls.sales_amount) AS revenue
FROM gold.dim_products AS pr
LEFT JOIN gold.fact_sales AS sls
ON pr.product_key = sls.product_key
GROUP BY pr.product_name 
ORDER BY revenue ASC


--which 5 product generate the worst revenue ?
SELECT TOP 5 
	pr.product_name,
	SUM(sls.sales_amount) AS revenue
FROM gold.dim_products AS pr
LEFT JOIN gold.fact_sales AS sls
ON pr.product_key = sls.product_key
GROUP BY pr.product_name 
ORDER BY revenue ASC


--top 10 customers with highest revenue
SELECT TOP 10	
	cu.first_name,
	cu.last_name,
	SUM(fs.sales_amount) AS revenue_generated 
FROM gold.dim_customers AS cu
LEFT JOIN gold.fact_sales AS fs
ON cu.customer_key = fs.customer_key
GROUP BY cu.first_name,
	     cu.last_name
ORDER BY revenue_generated DESC
